openapi: 3.0.0
info:
    title: Agents API
    description: Agents API Open AI Specification
    version: 1.0.0
servers:
    - url: https://agents.api.aimpact.partners
paths:
    /:
        get:
            tags:
                - Main
            responses:
                200:
                    description: Home API endpoint
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: boolean
                                    data:
                                        type: array

components:
    securitySchemes:
        firebaseId:
            type: http
            scheme: bearer
            bearerFormat: JWT
            description: Firebase ID token for authentication
